# Generated by Django 3.1.2 on 2020-10-23 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('number_order', models.AutoField(primary_key=True, serialize=False)),
                ('date_order', models.DateField(auto_now_add=True, verbose_name='Date order')),
                ('price_order', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Summary order')),
                ('contractor', models.CharField(max_length=255, verbose_name='Contractor')),
                ('description', models.TextField(verbose_name='Description order')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Ordering',
            },
        ),
    ]
